language: node_js
node_js:
 - "node"

branches:
  only:
    - master

before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3

script:
 - npm run lint
 - npm run test:ci
 - npm run build:prod
